### ISSUE TITLE
[FEAT] [GET] ~/category api 구현

### ISSUE THREAD

**Issue by huiseon37** [SOPT-31th-Seminar-10/Server-Welaaa#1]
## 🔨 요구 사항 
category 리스트 get api를 구현할거에요

## 📝 TODO 
- [ ] category controller 작성
- [ ] category service 작성
- [ ] category router 작성
